### ISSUE TITLE
Error with multiple UTM timezones

### ISSUE THREAD

**Issue by estebangatillo** [ranghetti/sen2r#366] opened 2020-12-22 01:29 UTC
Hi I haven’t been able to determine a solution to this error message: 

`Error in compareRaster(rasters) : different extent
Calls: stack ... stack -> .local -> addLayer -> addLayer -> compareRaster`

I reached out to the SCI Team Copernicus Services Coordinated Interface and they said this:

“Your AOI occupies two UTM Zones, with Tile 18TYL straddling the two zones:
Moreover, the feedback from the L2A expertise notes that the your code returns the “Error in compareRaster(rasters) : different extent” message. Thus, it may be that you are trying to compare areas that are in different UTM projections, and this causes the error message.
 
It is also noted that of the three dates of the L2A products for Tile 19TCF, two of them are at the easternmost edge of the swath. These two products are from Relative Orbit 11, where the other is from Relative Orbit 111 – and from within the swath, rather than being at the edge.”
 

I had previously downloaded and processed data from multiple orbits with no issues. I don’t understand why different UTM zones would cause an extent issue...the projection of each tile should be the same, no?
 
Do you have any insights into this error?

Here is the code I've been using that has worked dozens of times before this without issue:

```r
sen2r(gui = FALSE,
        timewindow = c(start_date, end_date),
        timeperiod = time_period_type,
        extent = extent_path,
        extent_name = city_name,
        list_prods = c("BOA"),
        max_cloud_safe = max_cloud,
        mask_type = NA, # no mask
        res_s2 = res_s2,
        extent_as_mask = extent_as_mask,
        parallel = detectCores()-1,
        processing_order = "3", # 3 is fastest but consumes more disk
        step_atmcorr = atmcorr_type,
        overwrite = F,
        overwrite_safe = F,
        rm_safe = "no",
        path_l1c = "./data/sentinel-2/sen2r-in", path_l2a = "./data/sentinel-2/sen2r-in",
        path_out = "./data/sentinel-2/sen2r-out")
  
  # Create list of sentinel-2 processed raster files
  sen_files <- list.files("./data/sentinel-2/sen2r-out/BOA", "\\.tif$", full.names = T)
  
  # Conditionally process composite rasters based on new data
  if(length(sen_files) > 0) {
    if(length(sen_files) > previous_sen_files) {
      # Combine all sentinel observations into single stack 
      sen_stack <- stack(sen_files)
      # Determine percent NA in composite layers for each band 
      composite_pct_na <- composite_bands(sen_stack, custom_extent) %>% unlist
```

**Comment by ranghetti** [comment] 2020-12-22 07:13
> I don’t understand why different UTM zones would cause an extent issue...the projection of each tile should be the same, no?

Hi, to answer to your general question here above: when the extent covers tiles with different UTM zones, some of them must be reprojected in order to be merged all together. The described error probably occurred at this stage, which is not performed "normally" (when all the tiles deal with the same projection). This is independent with the situation in which multiple orbits are involved, since images coming from different orbits are not merged.

To undestand the reason of your specific error I need additional information: please open an issue with the template "Help needed". You can also continue this issue, but follow the template which appears clicking on "Help needed" new issue to provide the required information, with particular care to code reproducibility (the code you provided is not reproducible).

**Comment by estebangatillo** [comment] 2020-12-30 22:38
Thank you for the insight! The reproducibility of this error is a bit complicated - I've run this exact code for a number of places at a number of different times and this is the first I've had this problem. To reproduce I'll need to share the exact spatial extent and I'll have to host that on webspace somewhere. Until then, I'm going to use information you provided to attempt to solve the problem, and if I'm unable to make progress I'll reach out again. Thank you thank you, and happy new year.

**Comment by ranghetti** [comment] 2021-01-02 07:30
You can attach it on your GitHub message. Otherwise, you can verify if using `extent = st_as_sfc(st_bbox(st_read(extent_path)))` instead than `extent = extent_path` would lead to the same error; if so, you can simply report `st_bbox(st_read(extent_path))` directly in the text.
In the meanwhile I am closing this and eventually waiting for the new issue.

**Closed by ranghetti** 2021-01-02 07:30 UTC
Labels: question
