### ISSUE TITLE
error while using sen2r tool in GUI mode

### ISSUE THREAD

**Issue by amit-srivastava79** [ranghetti/sen2r#141] opened 2018-12-16 10:53 UTC
I want o download Sentinel-2 and EVI through R. I came across your sen2r toolbox and was trying to use it in GUI mode. However, I am not able to feed my login and password of scihub in it (it closes every time I try to save it) also I am not able to "save as" because filename section remains inactive.
When without scihub login I run the tool, it gives following error.

[2018-12-14 16:35:46] Gui closed by the user. Starting processing.
[2018-12-14 16:35:46] Searching for available SAFE products on SciHub...
[2018-12-14 16:36:52] Computing output names...
Error in if (is.na(apihub_path)) { : argument is of length zero

It would very helpful if you could please let me know, is it because of login issue or am I doing something wrong?
Thank you!

**Comment by ranghetti** [comment] 2019-01-07 08:00
Sorry for my late reply, for some reasone I did not see the notification of your issue.
I should have fixed now, can you reinstall the package and check it?
Thanks

**Comment by amit-srivastava79** [comment] 2019-01-07 08:45
Thank you, I will reinstall and check it!

**Comment by amit-srivastava79** [comment] 2019-01-07 10:14
Hi Luigi

I am getting the following error after reinstalling and running the GUI. Howver it do consider my Login this time.
[2019-01-07 15:32:41] Starting sen2r execution.
[2019-01-07 15:32:42] Launching GUI...

Listening on http://127.0.0.1:4629
[2019-01-07 15:38:39] Gui closed by the user. Starting processing.
[2019-01-07 15:38:39] Searching for available SAFE products on SciHub...
[2019-01-07 15:39:59] Computing output names...
[2019-01-07 15:42:43] Execution of sen2r session terminated.

**Comment by ranghetti** [comment] 2019-01-07 10:19
It seems that processing was ended without finding/creating any new product. Can you save your parameters in a JSON file and post it?

**Comment by amit-srivastava79** [comment] 2019-01-07 10:35
Hi Luigi

Thanks for the prompt response. GitHub doesn't support to send JSON. Is it fine if I send it on your email? (ranghetti.l@irea.cnr.it)

**Comment by ranghetti** [comment] 2019-01-07 10:38
You can paste the content of the file (it is a text file).

**Comment by amit-srivastava79** [comment] 2019-01-07 10:38
Thanks, Here it is.

{
  "preprocess": [true],
  "s2_levels": ["l1c", "l2a"],
  "sel_sensor": ["s2a", "s2b"],
  "online": [true],
  "downloader": ["wget"],
  "overwrite_safe": [false],
  "rm_safe": ["no"],
  "max_cloud_safe": [100],
  "step_atmcorr": ["auto"],
  "timewindow": ["2018-10-09", "2019-01-07"],
  "timeperiod": ["full"],
  "extent": ["{\n  \"type\": \"FeatureCollection\",\n  \"features\": [\n    {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"_leaflet_id\": 480,\n        \"feature_type\": \"rectangle\"\n      },\n      \"geometry\": {\n        \"type\": \"Polygon\",\n        \"coordinates\": [\n          [\n            [85.224724, 25.686707],\n            [85.224724, 25.691038],\n            [85.226097, 25.691038],\n            [85.226097, 25.686707],\n            [85.224724, 25.686707]\n          ]\n        ]\n      }\n    },\n    {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"_leaflet_id\": 484,\n        \"feature_type\": \"rectangle\"\n      },\n      \"geometry\": {\n        \"type\": \"Polygon\",\n        \"coordinates\": [\n          [\n            [85.183525, 25.686088],\n            [85.183525, 25.738055],\n            [85.228844, 25.738055],\n            [85.228844, 25.686088],\n            [85.183525, 25.686088]\n          ]\n        ]\n      }\n    }\n  ]\n}"],
  "s2tiles_selected": ["45RUJ"],
  "s2orbits_selected": [null],
  "list_prods": ["BOA"],
  "list_indices": ["EVI2"],
  "list_rgb": [null],
  "rgb_ranges": [null],
  "index_source": ["BOA"],
  "mask_type": [null],
  "max_mask": [80],
  "mask_smooth": [0],
  "mask_buffer": [0],
  "clip_on_extent": [true],
  "extent_as_mask": [false],
  "extent_name": ["sen2r"],
  "reference_path": [null],
  "res": [null],
  "res_s2": ["10m"],
  "unit": ["Meter"],
  "proj": [null],
  "resampling": ["near"],
  "resampling_scl": ["near"],
  "outformat": ["GTiff"],
  "index_datatype": ["Int16"],
  "compression": ["DEFLATE"],
  "overwrite": [false],
  "path_l1c": ["D:/Sentinel_data/Level1C"],
  "path_l2a": ["D:/Sentinel_data/Level2A"],
  "path_tiles": [null],
  "path_merged": [null],
  "path_out": ["D:/Sentinel_data/sd"],
  "path_rgb": [null],
  "path_indices": ["D:/Sentinel_data/spectral_indices"],
  "path_subdirs": [true],
  "thumbnails": [true],
  "pkg_version": ["0.3.4"]
}

**Comment by ranghetti** [comment] 2019-01-07 11:45
Unfortunately I am not able to reproduce the error (the output is produced on my machine).
Are path_l1c, path_l2a, path_out and path_indices empty?

**Comment by amit-srivastava79** [comment] 2019-01-07 11:48
Yes, they are empty! Do you suggest I should try again?

**Comment by ranghetti** [comment] 2019-01-07 11:53
If the problem is related to SciHub connectivity, you should check your credentials and try to launch the processing again in a second time. 
Otherwise, it could be useful to update R to version 3.5, update all R packages, reinstall the library, use `check_sen2r_deps()`to install internal dependencies and try running again.
If you are using sen2r taking the parameters from an extenral JSON file (but it does not seem your case), also check that no files ending with "_ignorelist.txt" are present in the directory in which the JSON is stored.

**Comment by amit-srivastava79** [comment] 2019-01-07 11:57
Thanks Luigi !! I will get back to you if any issue crops out. I have R 3.5.1.
Credentials seem to be fine. ill do all the possible things you suggested.
thanks again!

**Comment by amit-srivastava79** [comment] 2019-01-08 05:57
I tried reinstalling everything, checked check_sen2r_deps(),My credentials are working fine as I download a sentinel-2A image from there. I also tried it on a different computer this time. 
The error I am getting is
> sen2r()
[2019-01-08 11:13:24] Starting sen2r execution.
[2019-01-08 11:13:25] Launching GUI...

Listening on http://127.0.0.1:4905
[2019-01-08 11:17:11] Gui closed by the user. Starting processing.
[2019-01-08 11:17:11] Searching for available SAFE products on SciHub...
[2019-01-08 11:18:19] Computing output names...
Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
[2019-01-08 11:20:54] Execution of sen2r session terminated.

Am I missing something which I shouldn't be?
thanks!

**Comment by ranghetti** [comment] 2019-01-09 07:56
Yesterday I saw a similar issue on another Windows PC, but launching again the processing was sufficient to solve it (for this reason, I cannot debug it and understand its reason). The only difference was that I launched the processing without opening the GUI:
```r
sen2r("/path/of/the/saved/parameter/file.json")
```
Maybe you can try in this way.

**Comment by amit-srivastava79** [comment] 2019-01-09 08:42
Many Thanks Luigi! This method is working, will update when it finishes!!

**Comment by ranghetti** [comment] 2019-01-10 14:30
Now the processing should work also in GUI mode.

**Comment by amit-srivastava79** [comment] 2019-01-11 03:55
That's great !! Thanks Luigi! Your tool is really helpful

**Closed** 2019-01-16 10:13 UTC
