### ISSUE TITLE
Incomplete output images

### ISSUE THREAD

**Issue by agronomofiorentini** [ranghetti/sen2r#353] opened 2020-10-08 06:45 UTC
I have the same problem as reported in #329 in Sardegna (Italy).
I kindly ask to @ranghetti to fix this.

I think is again about "different CRSs problem".

I will post the thumbnails output of sen2r and also i will attach the r code.

Thanks

![S2A2A_20200401_065_Sardegna_BOA_10](https://user-images.githubusercontent.com/66969646/95424155-8b084a80-0942-11eb-89cf-39f2bbfb8eeb.jpg)
![S2A2A_20200408_022_Sardegna_BOA_10](https://user-images.githubusercontent.com/66969646/95424157-8c397780-0942-11eb-8959-dab3643e87bc.jpg)
![S2A2A_20200411_065_Sardegna_BOA_10](https://user-images.githubusercontent.com/66969646/95424161-8cd20e00-0942-11eb-8e3e-ebb14b92d490.jpg)

sen2r(gui = FALSE,
      extent = sardegna,
      extent_name = "Sardegna",
      extent_as_mask = TRUE,
      s2tiles_selected = c("32TML", "32TNL", 
                           "32TMK", "32TNK", 
                           "32SMJ", "32SNJ"),
      timewindow = c(as.Date("2020-04-01"), as.Date("2020-04-30")),
      timeperiod = "full",
      list_prods = "BOA",
      s2_levels = "l2a",
      step_atmcorr = "l2a",
      overwrite_safe = TRUE,
      rm_safe = "yes",
      online = TRUE,
      proj = "+proj=longlat +datum=WGS84",
      sel_sensor = c("s2a", "s2b"),
      outformat = "GTiff",
      max_cloud_safe = 20,
      parallel = TRUE,
      path_l2a = "F:/Sentinel_2_images/sentinel_2_images_sen2r_sardegna",
      path_out = "F:/Sentinel_2_images/sentinel_2_images_sen2r_sardegna")

**Comment by ranghetti** [comment] 2020-10-11 04:56
These cases are not related to different CRSs problems.
I will not be at work until October 18th; I will deepen this issue as soon as possible.

**Comment by ranghetti** [comment] 2020-10-19 06:24
The reason for which images are not complete is multiple.

1. **Partial orbit coverage**: orbit 22 only covers the western part of Sardinia (first thumbnail here below), while orbit 65 covers almost all the island, with the exception of the Nurra (second thumbnail); so, all the dates dealing with orbit 22 will cover _at most_ the area covered by your third image, and all the dates dealing with orbit 65 will not include a little portion of the Nurra (the north-western area which is missing in your second image).
![image](https://user-images.githubusercontent.com/6874239/96407962-d512eb00-11e2-11eb-8961-9f94a8c21602.png) ![image](https://user-images.githubusercontent.com/6874239/96407973-d93f0880-11e2-11eb-8ab1-681812b801ad.png)

2. **Maximum cloud SAFE**: you set argument `max_cloud_safe` to 20, meaning that SAFE archives characterised by a cloud coverage > 20% are not downloaded and used; this is the reason why two tiles (south-western portion) are missing in your first image. To avoid that, do not use argument `max_cloud_safe`.

3. **Splitted tiles**: for some reasons, sometimes (very rarely) tiles are splitted in two products (bold areas in the first thumbnail above); in this case, {sen2r} only uses one of the two. This is a bug which i still have to manage (in your case, this bug affects only the missing north-eastern portion in northern Gallura region in the specific image of the 11th April).

**Comment by agronomofiorentini** [comment] 2020-10-19 12:32
Thank you very much for the exhaustive explanation.
I will try to perform the processing as suggested.

For the splitted tiles issue i hope that you find the solution cause this package is one of my favorite package.

Thanks again

**Comment by ranghetti** [comment] 2020-10-21 08:11
> For the splitted tiles issue i hope that you find the solution cause this package is one of my favorite.

Actually it is not simple to fix: the package is based on the recognition of "equivalent" products basing on the correspondence of mission (S2A/S2B), level (1C/2A), date of acquisition, tile ID and orbit ID. Basing on that, these "splitted" products are equivalent. Managing this bug would require to find another way to distinguish "equivalent" products (i.e. basing on footprints, but in a "smart" way to avoid distinguishing equivalent products if footprints are slightly different), and to apply that to several code chunks. I will do it, but it will require a high amount of time.

**Comment by ranghetti** [comment] 2020-11-09 15:41
@agronomofiorentini I have added the possibility to manage splitted tiles in the GitHub version 1.3.9.9001 of the package. As a side effect, now nodata values (black areas) are set to NA instead than left to 0.
You can install it with
```r
install.packages("remotes")
remotes::install_github("ranghetti/sen2r")
```

Since this is an improvement which potentially could affect other parts of the code of the whole package, please let me know if all is working as expected.

**Comment by agronomofiorentini** [comment] 2020-11-10 07:38
@ranghetti thank you for the effort, i really appreciate.

I will try it and i will let you know.

**Comment by agronomofiorentini** [comment] 2020-11-18 13:15
@ranghetti I am sorry for late reply.

This morning I ran the following code

```
sen2r(gui = FALSE,
      extent = sardegna,
      extent_name = "Sardegna",
      extent_as_mask = TRUE,
      s2tiles_selected = c("32TML", "32TNL", 
                           "32TMK", "32TNK", 
                           "32SMJ", "32SNJ"),
      s2orbits_selected = 22,
      timewindow = c(as.Date("2020-04-15"), as.Date("2020-04-30")),
      timeperiod = "full",
      list_prods = "BOA",
      s2_levels = "l2a",
      step_atmcorr = "l2a",
      overwrite_safe = TRUE,
      rm_safe = "yes",
      online = TRUE,
      proj = "+proj=longlat +datum=WGS84",
      sel_sensor = c("s2a", "s2b"),
      outformat = "GTiff",
      parallel = TRUE,
      path_l2a = "G:/Sentinel_2_images/sentinel_2_images_sen2r_sardegna",
      path_out = "G:/Sentinel_2_images/sentinel_2_images_sen2r_sardegna")

```

The results was great.

**Comment by ranghetti** [comment] 2020-11-18 13:33
@agronomofiorentini have you checked if the issue got solved? If so, please let me know before closing it.

**Comment by agronomofiorentini** [comment] 2020-11-18 13:48
@ranghetti i am sorry for the late reply.

yes, this morning I tried to run this code without specifying the s2orbits_selected = 22.
The code isn't like the first one reported in this issue as you will see, if it is necessary for you I will try by the evening or tomorrow at the latest to do the processing and send you the results always here


```
sen2r(gui = FALSE,
      extent = sardegna,
      extent_name = "Sardegna",
      extent_as_mask = TRUE,
      s2tiles_selected = c("32TML", "32TNL", 
                           "32TMK", "32TNK", 
                           "32SMJ", "32SNJ"),
      timewindow = c(as.Date("2020-04-15"), as.Date("2020-04-30")),
      timeperiod = "full",
      list_prods = "BOA",
      s2_levels = "l2a",
      step_atmcorr = "l2a",
      overwrite_safe = TRUE,
      rm_safe = "yes",
      online = TRUE,
      proj = "+proj=longlat +datum=WGS84",
      sel_sensor = c("s2a", "s2b"),
      outformat = "GTiff",
      parallel = TRUE,
      path_l2a = "G:/Sentinel_2_images/sentinel_2_images_sen2r_sardegna",
      path_out = "G:/Sentinel_2_images/sentinel_2_images_sen2r_sardegna")

```

and the result is as follows.

![S2A2A_20200418_022_Sardegna_BOA_10](https://user-images.githubusercontent.com/66969646/99537738-57dac180-29ac-11eb-9926-6d46c5465aca.jpg)
![S2A2A_20200421_065_Sardegna_BOA_10](https://user-images.githubusercontent.com/66969646/99537741-58735800-29ac-11eb-8d54-5e872aa0f10f.jpg)
![S2A2A_20200428_022_Sardegna_BOA_10](https://user-images.githubusercontent.com/66969646/99537743-590bee80-29ac-11eb-856e-0935d499eaaf.jpg)
![S2B2A_20200416_065_Sardegna_BOA_10](https://user-images.githubusercontent.com/66969646/99537746-5a3d1b80-29ac-11eb-85ba-ec1a26b063c1.jpg)
![S2B2A_20200423_022_Sardegna_BOA_10](https://user-images.githubusercontent.com/66969646/99537749-5a3d1b80-29ac-11eb-87db-9b6ac4bbee7f.jpg)
![S2B2A_20200426_065_Sardegna_BOA_10](https://user-images.githubusercontent.com/66969646/99537751-5ad5b200-29ac-11eb-95e0-24b8ffa698f7.jpg)

I would like to run the same code but adding the argument  s2orbits_selected = 22 and then i would like to let you know.

**Comment by ranghetti** [comment] 2020-11-18 13:55
No, it is not necessary to run the same code (at the opposite, it is better to have a look to a wider situation).
I am seeing the same problem in the 2020-04-23 image. I will try to reproduce it.

**Comment by agronomofiorentini** [comment] 2020-11-18 13:58
if you need me, I'm here.

Thank you very much

**Comment by ranghetti** [comment] 2020-11-20 13:38
Ok, it should be fixed now. Can you try reinstalling and re-running?

**Comment by agronomofiorentini** [comment] 2020-11-20 13:43
Yes i will do it this afternoon.
As soon as possible i will let you know the results.

**Comment by agronomofiorentini** [comment] 2020-11-20 17:59
I ran again the follow code

```
sen2r(gui = FALSE,
      extent = sardegna,
      extent_name = "Sardegna",
      extent_as_mask = TRUE,
      s2tiles_selected = c("32TML", "32TNL", 
                           "32TMK", "32TNK", 
                           "32SMJ", "32SNJ"),
      #s2orbits_selected = 22,
      timewindow = c(as.Date("2020-04-15"), as.Date("2020-04-30")),
      timeperiod = "full",
      list_prods = "BOA",
      s2_levels = "l2a",
      step_atmcorr = "l2a",
      overwrite_safe = TRUE,
      rm_safe = "yes",
      online = TRUE,
      proj = "+proj=longlat +datum=WGS84",
      sel_sensor = c("s2a", "s2b"),
      outformat = "GTiff",
      parallel = TRUE,
      path_l2a = "G:/Sentinel_2_images/sentinel_2_images_sen2r_sardegna",
      path_out = "G:/Sentinel_2_images/sentinel_2_images_sen2r_sardegna")
```

and this is the result.

![S2B2A_20200423_022_Sardegna_BOA_10](https://user-images.githubusercontent.com/66969646/99833448-4804de00-2b62-11eb-86d7-dbc7fdae37db.jpg).
![S2B2A_20200426_065_Sardegna_BOA_10](https://user-images.githubusercontent.com/66969646/99833451-489d7480-2b62-11eb-9f08-6635286fbe00.jpg)
![S2A2A_20200418_022_Sardegna_BOA_10](https://user-images.githubusercontent.com/66969646/99833439-463b1a80-2b62-11eb-8185-f51fb6b46794.jpg)
![S2A2A_20200421_065_Sardegna_BOA_10](https://user-images.githubusercontent.com/66969646/99833442-46d3b100-2b62-11eb-9572-229ebd6079d8.jpg)
![S2A2A_20200428_022_Sardegna_BOA_10](https://user-images.githubusercontent.com/66969646/99833444-476c4780-2b62-11eb-8297-fd4e13a4950f.jpg)
![S2B2A_20200416_065_Sardegna_BOA_10](https://user-images.githubusercontent.com/66969646/99833446-4804de00-2b62-11eb-8208-a4a4a16f67ce.jpg)

compared to before there is an improvement for the fifth image.

.

**Comment by ranghetti** [comment] 2020-11-20 20:01
Ok, this solves the issue (missing portions different from fifth image are due to point 1 of https://github.com/ranghetti/sen2r/issues/353#issuecomment-711641473).
I leave this issue open until you will finish your processing. When you will have finished it, feel free to close it if you will not have found any other problem.

**Closed** 2020-11-20 20:05 UTC
Labels: bug, question
