### ISSUE TITLE
Sen2Cor configuration file was not found in its default directory

### ISSUE THREAD

**Issue by JakobRieser** [ranghetti/sen2r#318] opened 2020-05-26 13:12 UTC
Hi,

i want to use Sen2Cor in sen2r for processing level-1C Sentinel2AB data. But when i start processing it immediately fails with the following error message: 

```
Starting to correct level-1C SAFE products with Sen2Cor. This operation could take very long time.
Error in { : task 1 failed - "task 1 failed - "
Sen2Cor configuration file was not found in its default directory""
In addition: Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="D:/Daten/Dokumente/sen2cor/2.5/cfg/L2A_GIPP.xml": The system cannot find the path specified
```

When i check, if Sen2Cor is installed correctly via check_sen2r_deps() it is. I deleted and reinstalled sen2r and Sen2Cor but it didn't help. I always used the default settings and directories. What can i do to get the configuration file, where it belongs?

edit:
sen2r version: 1.3.4.9003
R version: 4.0.0 (2020-04-24)
OS: Windows 10 x64
System: x86_64, mingw32
UI: RStudio

**Comment by ranghetti** [comment] 2020-05-26 14:22
Hi, the package is configured to find the Sen2Cor GIPP file at `~\sen2cor\2.5\cfg\L2A_GIPP.xml`, which is the path where Sen2Cor places it. Is it present?

If neither (as the error message suggests): in which way did you configured Sen2Cor? Did you install ("Install a new Sen2Cor environment") or link it ("Set the path of an existing Sen2Cor")? In this second case, try installing it using the first option (the Sen2Cor installation process creates this file). After doing that, you will receive an output message in the console, containing the path of this GIPP file. In case reinstalling it will not solve, paste that message.

**Comment by JakobRieser** [comment] 2020-05-26 15:24
Hi, thank you for your fast response!

I did "Install a new Sen2Cor environment", but the file was not present. I did it again now and this was my console output:

```
Listening on http://127.0.0.1:6168
  |=================================================================================================================================================================| 100%
<simpleError: 
Sen2Cor configuration file was not found in its default directory>
Warning: Error in writeImpl: Text to be written must be a length-one character vector
  84: stop
  83: writeImpl
  82: textWriter$write
  81: tagWrite
  80: tagWrite
  79: tagWrite
  78: doRenderTags
  77: renderTags
  76: as.character.shiny.tag
  73: observeEventHandler
   2: runApp
   1: check_sen2r_deps
```

**Comment by ranghetti** [comment] 2020-05-26 15:40
Try repeating the installation using function `install_sen2cor()`: this should return a verbose console output about Sen2Cor installation, like the following:
```
> install_sen2cor()
  |=====================================================================================================| 100%
Default Sen2Cor parameters were written in file
"C:\Users\LRANGH~1\DOCUME~1\SEN2R~1\sen2r_L2A_GIPP.xml".
IMPORTANT NOTE: for backward compatibility, the parameter "DEM_Directory" was maitained to its
default value. This does not grant homogeneity between Level-2A SAFE products generated locally
with Sen2Cor and downloaded from ESA Hub (which make use of DEM for topographic correction and
ESA-CCI data-package.).
In order to allor Sen2Cor performing topographic correction, use functions sen2cor() and sen2r()
with the following arguments:
  sen2cor(..., use_dem = TRUE)
  sen2r(..., sen2cor_use_dem = TRUE)
or properly set the sen2r GUI. In a future sen2r release, this will be the default behaviour.
To use ESA-CCI data-package, download it at http://maps.elie.ucl.ac.be/CCI/viewer/download.php and
install it (further information can be found at
http://step.esa.int/main/third-party-plugins-2/sen2cor/).
```

If so, check what is present in the directory reported after line `Default Sen2Cor parameters were written in file` (in my case `C:\Users\LRANGH~1\DOCUME~1\SEN2R~1`).

**Comment by JakobRieser** [comment] 2020-05-26 15:56
I tried but unfortunately this error appears:

```
> install_sen2cor()
Error in print_message(type = "message", "Sen2Cor is already installed; to overwrite, set force = TRUE.") : 
  could not find function "print_message"
> install_sen2cor(force = T)
Error in print_message(type = "waiting", sen2cor_dir, " already exists and will be erased: ENTER to proceed or ESC to cancel...") : 
  could not find function "print_message"
```

**Comment by ranghetti** [comment] 2020-05-26 16:16
I cannot explain that: `print_message()` is an internal sen2r function, and must be found by other sen2r functions.

By the way, report your system information and sen2r version as stated at #186. Then you could try with a clean sen2r and/or R reinstallation.

**Comment by JakobRieser** [comment] 2020-05-26 16:33
Yeah, it also seemed pretty weird to me. 

sen2r version: 1.3.4.9003 
R version: 4.0.0 (2020-04-24)
OS: Windows 10 x64              
System: x86_64, mingw32             
UI: RStudio

I will - again - try a clean reinstallation of R, sen2r and sen2cor.

**Comment by JakobRieser** [comment] 2020-05-26 19:17
Alright, i unistalled sen2r, Sen2Cor, R and all folders connected to any of it. Installed everything again and unfortunately the installation of Sen2Cor with sen2r resulted in the exact same output as before:

```
Listening on http://127.0.0.1:3135
  |=================================================================================================================================================================| 100%
<simpleError: 
Sen2Cor configuration file was not found in its default directory>
Warning: Error in writeImpl: Text to be written must be a length-one character vector
  84: stop
  83: writeImpl
  82: textWriter$write
  81: tagWrite
  80: tagWrite
  79: tagWrite
  78: doRenderTags
  77: renderTags
  76: as.character.shiny.tag
  73: observeEventHandler
   2: runApp
   1: check_sen2r_deps

```
Same with install_sen2cor() command:  
```
> install_sen2cor()
Error in print_message(type = "message", "Sen2Cor is already installed; to overwrite, set force = TRUE.") : 
  could not find function "print_message"
```

**Comment by ranghetti** [comment] 2020-05-27 05:26
It is correct that the two directories are different: the second is the path in which you choosed to install Sen2Cor (in this case, the default directory set by sen2r); the first one corresponds to `$SEN2COR_HOME`, which is a path set by Sen2Cor itself for configuration files.
So Sen2Cor was correctly installed. The issue is still related to the fact that your installation cannot find internal function `print_message()` when called here:
https://github.com/ranghetti/sen2r/blob/8823ccc8f67eefea905d24d15639a21580056d3d/R/gipp.R#L73

What does it happen when calling `print_message()` in other situations, e.g. launching `sen2r()`? Do you see the following message?
```
[2020-05-27 07:20:20] #### Starting sen2r execution. ####
[2020-05-27 07:20:21] Launching GUI...
```
Moreover, what about launching `sen2r:::print_message(type = "message", "Test")`?

**Comment by JakobRieser** [comment] 2020-05-27 18:33
```
> sen2r()
[2020-05-27 20:31:28] #### Starting sen2r execution. ####
[2020-05-27 20:31:28] Launching GUI...
Loading required package: shiny
 
> sen2r:::print_message(type = "message", "Test")
Test
```

**Comment by ranghetti** [comment] 2020-05-28 06:06
Even stranger; but better: if the `print_message()` issue is limited to Sen2Cor installation, you can manually set it and continuing using the package.
To do it, you have to edit the file `paths.json` adding a Sen2Cor entry. Follow indications in #300, in which GDAL paths were manually added; in your case, add the following entry: 
```
"sen2cor": ["D:\\Daten\\Dokumente\\.sen2r\\sen2cor\\Sen2Cor-02.05.05-win64\\bin\\L2A_Process.bat"]
```
(before doing that, check that `D:\Daten\Dokumente\.sen2r\sen2cor\Sen2Cor-02.05.05-win64\bin\L2A_Process.bat` is the correct path)

**Comment by JakobRieser** [comment] 2020-05-28 22:05
So i had a look at paths.json and the entry you suggested me to add is already there and linking to the L2A_Process.bat file, which is present in the correct directory. So the problem must be somewhere else.

**Comment by ranghetti** [comment] 2020-05-29 00:24
Not necessarily: print_message() was called at the end of the function, after Sen2Cor configuration. Simply try using the package, It may be that you will no more encounter It (conversely, report it again).

**Comment by JakobRieser** [comment] 2020-06-02 19:43
Unfortunately, still getting the same error when trying to use sen2cor:

```
> sen2r()
[2020-06-02 21:37:26] #### Starting sen2r execution. ####
[2020-06-02 21:37:26] Launching GUI...

Listening on http://127.0.0.1:6106
Warning: Parameter "apihub" was not specified; setting it to the default ('NA').
Loading required namespace: stringi
Warning: 'geojsonlint' not installed, skipping GeoJSON linting
[2020-06-02 21:42:28] Gui closed by the user. Starting processing.
[2020-06-02 21:42:28] Computing output names...
Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
[2020-06-02 21:42:29] Starting to correct level-1C SAFE products with Sen2Cor. This operation could take very long time.
Error in { : task 1 failed - "task 1 failed - "
Sen2Cor configuration file was not found in its default directory""
In addition: Warning messages:
1: 'geojsonlint' not installed, skipping GeoJSON linting 
2: In set(x, j = name, value = value) :
  Column 'footprint' does not exist to remove
3: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="D:/Daten/Dokumente/sen2cor/2.5/cfg/L2A_GIPP.xml": The system cannot find the path specified
```

**Comment by ranghetti** [comment] 2020-06-03 05:43
Have you checked that the Sen2Cor configuration file actually exists?
```r
file.exists("D:\\Daten\\Dokumente\\.sen2r\\sen2cor\\Sen2Cor-02.05.05-win64\\bin\\L2A_Process.bat")
list.files("D:\\Daten\\Dokumente\\.sen2r\\sen2cor\\Sen2Cor-02.05.05-win64\\bin")
```

**Comment by JakobRieser** [comment] 2020-06-03 19:37
It does not exist in this specific directory:
```
> file.exists("D:\\Daten\\Dokumente\\.sen2r\\sen2cor\\Sen2Cor-02.05.05-win64\\bin\\L2A_Process.bat")
[1] FALSE
> list.files("D:\\Daten\\Dokumente\\.sen2r\\sen2cor\\Sen2Cor-02.05.05-win64\\bin")
 [1] "expat.dll"            "gdal_translate.exe"   "gdal201.dll"          "gdaladdo.exe"         "gdalbuildvrt.exe"     "gdaldem.exe"          "gdalinfo.exe"        
 [8] "gdalwarp.exe"         "geotiff.dll"          "jpeg62.dll"           "libcharset.dll"       "libexslt.dll"         "libiconv.dll"         "libifcoremd.dll"     
[15] "libiomp5md.dll"       "libmmd.dll"           "libpng16.dll"         "libxml2.dll"          "libxslt.dll"          "mkl_avx.dll"          "mkl_core.dll"        
[22] "mkl_def.dll"          "mkl_intel_thread.dll" "mkl_rt.dll"           "msvcp120.dll"         "msvcr120.dll"         "ogrinfo.exe"          "openjp2.dll"         
[29] "proj.dll"             "python.exe"           "python27.dll"         "sqlite3.dll"          "tcl85.dll"            "tclpip85.dll"         "tiff.dll"            
[36] "tk85.dll"             "zlib.dll"            
> 
```
But in my case it is located in `D:\Daten\Dokumente\.sen2r\sen2cor\Sen2Cor-02.05.05-win64`

**Comment by ranghetti** [comment] 2020-06-04 05:50
Ok, the path without the subfolder `bin` is the correct path.

Let's recap the whole situation:

1. Sen2Cor is [seems to be] correctly installed;
2. `L2A_GIPP.xml` is not found;
3. `print_message()` is correctly found in several internal functions ut not in `gipp.R` line 73.

Abound point 2: the path in which `L2A_GIPP.xml` is searched is defined here: https://github.com/ranghetti/sen2r/blob/7922a00e6695678e86cc3b2f09c894812051e25f/R/gipp.R#L57-L60
The output of this chunk should be `C:\Users\Rieser\Documents\sen2cor\2.5\cfg\L2A_GIPP.xml` (in the shortened form), where at https://github.com/ranghetti/sen2r/issues/318#issuecomment-634224495 you declared the xml file to be present. Run that chunk to ensure that: if the two paths correspond and the file exists, I would have no more solutions to propose you (the error would definitively not be related to sen2r). Otherwise, copy the xml from the existing path to the path returned by that code chunk. In every case, also copy the xml to `D:\Daten\Dokumente\.sen2r\sen2cor\Sen2Cor-02.05.05-win64` (I do not know why, but a warning says that it is searched also in that location -- actually it should not).

**Comment by JakobRieser** [comment] 2020-06-04 20:31
So when i run this i get
```
> gipp_sen2cor_path <- normalize_path(file.path("~/sen2cor", 2.5, "cfg/L2A_GIPP.xml")) 
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="D:/Daten/Dokumente/sen2cor/2.5/cfg/L2A_GIPP.xml": The system cannot find the path specified
```
which is the wrong path. In fact this path is not existing, as it should be `C:/Daten/Dokumente/sen2cor/2.5/cfg/L2A_GIPP.xml. `So i still think there is some kind of confusion with my different drives. That also means i cannot copy the `L2A_GIPP.xml` to that directory.  
Anyway i did copy it to `D:\Daten\Dokumente\.sen2r\sen2cor\Sen2Cor-02.05.05-win64` as you suggested but that didn't help. 
The question is can i get the system to search the xml in C:/ and not D:/?

**Comment by ranghetti** [comment] 2020-06-05 08:52
If the output of `normalizePath("~")` is `D:/Daten/Dokumente` instead than `C:\Users\Rieser\Documents` it means that your home directory is set to `D:` instead than to the default home path in Windows. This is a very strange system custom setting (which actually I did not even think to be possible, and which I never encountered), but I cannot change it in sen2r. Try first copying it to `D:/Daten/Dokumente/sen2cor/2.5/cfg/L2A_GIPP.xml` (different from the previous one). Then, if it will not help, try copying it to the directory which is returned by the following command:
```r
file.path(dirname(attr(sen2r::load_binpaths(), "path")), "sen2r_L2A_GIPP.xml")
```

**Comment by lbusett** [comment] 2020-06-08 16:24
@ranghetti 

  modifying the path of the Documents folder on Windows is not common, but also not rare. Many do that in order to have the Documents folder  on a different hard drive than the one where Windows is installed. For example, also on my Windows machine normalizePath("~") gives "D:/Documents"

**Comment by ranghetti** [comment] 2020-06-08 18:22
@lbusett can you make a test? Try installing Sen2Cor with function `install_sen2cor()`, then check if the file `L2A_GIPP.xml` has been placed in `C:\Users\<user>\Documents\sen2cor\2.5\cfg\L2A_GIPP.xml` instead than in `D:\Documents\sen2cor\2.5\cfg\L2A_GIPP.xml`. (This file is created by Sen2Cor installer, not by sen2r).
If so, I will change the code in https://github.com/ranghetti/sen2r/blob/7922a00e6695678e86cc3b2f09c894812051e25f/R/gipp.R#L57-L60 to always search the file `C:\Users\<user>\Documents`.

@JakobRieser were you able to fix following the suggestions in https://github.com/ranghetti/sen2r/issues/318#issuecomment-639349781?

**Comment by ranghetti** [comment] 2020-06-16 05:52
Closing after 10 days of @JakobRieser's missing feedback (#186).
@lbusett if you can make the test with on Windows (with documents on D) I can patch this situation.

**Comment by lbusett** [comment] 2020-06-26 08:12
@ranghetti 

I finally managed to check this. Sorry for the wait. 

Also on my machine, the file was created in "C:\Users\<user>\Documents", although my Documents folder is re-mapped to D:/Documents. Indeed, after using `install_sen2cor()`, I got the message: 

`> install_sen2cor()
  |================================================================================================================================================================| 100%

Error: 
Sen2Cor configuration file was not found in its default directory
In addition: Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="D:/Documents/sen2cor/2.5/cfg/L2A_GIPP.xml": The system cannot find the path specified`

**Comment by ranghetti** [comment] 2020-07-01 08:01
@lbusett can you try if the problem was fixed (reinstalling from devel)?

**Comment by lbusett** [comment] 2020-07-03 10:10
@ranghetti 

Now it installed no problem . How can I check if sen2r looks for the file in the correct path?

**Comment by ranghetti** [comment] 2020-07-03 11:24
> How can I check if sen2r looks for the file in the correct path?

If the installation finished fine, the file was found. The original file was searched in this directory:
```r
file.path(Sys.getenv("USERPROFILE"), "Documents/sen2cor/2.5/cfg/L2A_GIPP.xml")
```
instead than in the previous one (`~/Documents/sen2cor/2.5/cfg/L2A_GIPP.xml`).

If found, it is copied in
```r
file.path(dirname(attr(sen2r::load_binpaths(), "path")), "sen2r_L2A_GIPP.xml")
```
If you found the file in this last position, it was correctly copied.

**Comment by lbusett** [comment] 2020-07-03 11:58
@ranghetti 

The file is indeed in 

`file.path(Sys.getenv("USERPROFILE"), "Documents/sen2cor/2.5/cfg/L2A_GIPP.xml")`

```
file.exists(file.path(Sys.getenv("USERPROFILE"), "Documents/sen2cor/2.5/cfg/L2A_GIPP.xml"))
[1] TRUE

```
however, apparently it was not copied during installation: 

```
file.exists(file.path(dirname(attr(sen2r::load_binpaths(), "path")), "sen2r_L2A_GIPP.xml"))
[1] FALSE
```

**Comment by ranghetti** [comment] 2020-07-03 12:04
SenCor was actually reinstalled during the second installation (download of the archive + some time to unzip and configure)? Maybe this stes was skipped, if the Sen2Cor path was already present in `paths.json`. In this case, try with `install_sen2cor(force=TRUE)`.

**Comment by lbusett** [comment] 2020-07-03 12:06
ops... sorry... I forgot to issue install_sen2cor().... Checking now!

**Comment by lbusett** [comment] 2020-07-03 12:11
Yes, all seems to be ok now! Sorry !

**Comment by ranghetti** [comment] 2020-07-03 12:15
Thanks for the test!

**Closed by ranghetti** 2020-07-03 12:15 UTC
Labels: assistance, bug, missing feedback
