### ISSUE TITLE
Request failed [403] task 1 failed Md5sum check failed

### ISSUE THREAD

**Issue by VicenteYago** [ranghetti/sen2r#374] opened 2021-01-29 12:30 UTC
**Inputs**
param_file '`inputsV1-4-0-issue.json`: 
```{txt}
{
  "preprocess": [true],
  "s2_levels": ["l1c", "l2a"],
  "sel_sensor": ["s2a", "s2b"],
  "online": [true],
  "order_lta": [true],
  "downloader": ["builtin"],
  "overwrite_safe": [false],
  "rm_safe": ["no"],
  "max_cloud_safe": [100],
  "step_atmcorr": ["l2a"],
  "sen2cor_use_dem": [null],
  "sen2cor_gipp": [null],
  "timewindow": ["2019-02-24", "2019-02-26"],
  "timeperiod": ["full"],
  "extent": ["./pilotoV2.geojson"],
  "s2tiles_selected": [null],
  "s2orbits_selected": [null],
  "list_prods": ["BOA", "SCL"],
  "list_indices": ["NDMI", "NDVI", "NDWI", "NBR", "SAVI", "EVI"],
  "list_rgb": ["RGB432B"],
  "rgb_ranges": [[0, 2500]],
  "index_source": ["BOA"],
  "mask_type": [null],
  "max_mask": [100],
  "mask_smooth": [0],
  "mask_buffer": [0],
  "clip_on_extent": [true],
  "extent_as_mask": [true],
  "extent_name": ["pilotoV1"],
  "reference_path": [null],
  "res": [null],
  "res_s2": ["10m"],
  "unit": ["Meter"],
  "proj": [null],
  "resampling": ["near"],
  "resampling_scl": ["near"],
  "outformat": ["GTiff"],
  "rgb_outformat": ["GTiff"],
  "index_datatype": ["Float32"],
  "compression": ["DEFLATE"],
  "rgb_compression": ["DEFLATE"],
  "overwrite": [false],
  "path_l1c": ["./l1c"],
  "path_l2a": ["./l2a"],
  "path_tiles": [null],
  "path_merged": [null],
  "path_out": ["./out"],
  "path_rgb": [""],
  "path_indices": ["./indices"],
  "path_subdirs": [true],
  "thumbnails": [false],
  "log": ["./log.txt"],
  "parallel": [true],
  "processing_order": ["by_groups"],
  "pkg_version": ["1.4.0"]
}
```
extent `pilotoV2.geojson`: 

```{json}
"type":"FeatureCollection","features":[{"type":"Feature","id":0,"properties":{"dummy":0},"geometry":{"type":"Polygon","coordinates":[[[-0.879,38.5949],[-0.8785,38.5939],[-0.8783,38.5938],[-0.8777,38.5937],[-0.8773,38.5923],[-0.8773,38.5918],[-0.8775,38.5917],[-0.8806,38.5922],[-0.8806,38.5925],[-0.8806,38.5929],[-0.8806,38.5932],[-0.8807,38.5935],[-0.8812,38.5937],[-0.8816,38.5939],[-0.8817,38.5942],[-0.8817,38.5945],[-0.881,38.5946],[-0.8803,38.5947],[-0.88,38.5947],[-0.879,38.5949]]]}}]}
```

**Bug description**

Hi Luigi, im having multiple errors when using sen2r function.  The errors are similar in all of them. For example, the image taken in the date 2019-02-25: 

**Reproducible example**

```r
## 
library(sen2r)
example_extent <- "./pilotoV2.geojson"
# file example.shp _must_ be attached if not available online
output <-  sen2r(param_list = "./inputsV1-4-0-issue.json")
# file parameter_file.json _must_ be attached of copied as text
```

**Expected and actual behavior**
Since the image is in the LTA, (at the time of writing these lines), should sen2r() execution ends in this way or it should ends in a more controlled way.

```
[2020-12-21 16:17:01] #### Starting sen2r execution. ####
[2020-12-21 16:17:02] Searching for available SAFE products on SciHub...
[2020-12-21 16:17:10] Computing output names...
[2021-01-29 12:53:09] Starting to download the required level-2A SAFE products.
[2021-01-29 12:53:09] Check if products are available for download...
[2021-01-29 12:53:09] Downloading Sentinel-2 image 1 of 1
        (S2A_MSIL2A_20190225T105021_N0211_R051_T30SXH_20190225T134315.SAFE)...
  |====================================================================================| 100%
Request failed [403]. Retrying in 1 seconds...
  |====================================================================================| 100%
Request failed [403]. Retrying in 2.9 seconds...
  |====================================================================================| 100%
Error in { : 
  task 1 failed - "task 1 failed - "task 1 failed - "zip file './l2a/S2A_MSIL2A_20190225T105021_N0211_R051_T30SXH_20190225T134315.SAFE.zip' cannot be opened"""
In addition: Warning message:
'geojsonlint' not installed, skipping GeoJSON linting 
...
```

**System information**

sessionInfo()
```{r}
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] sf_0.9-7          jsonlite_1.7.2    magick_2.6.0      png_0.1-7         tiff_0.1-6       
 [6] gdalUtils_2.0.3.2 magrittr_2.0.1    rjson_0.2.20      xml2_1.3.2        raster_3.4-5     
[11] httr_1.4.2        RJSONIO_1.3-1.4   geojsonio_0.9.4   sp_1.4-4          forcats_0.5.0    
[16] stringr_1.4.0     dplyr_1.0.2       purrr_0.3.4       readr_1.4.0       tidyr_1.1.2      
[21] tibble_3.0.4      ggplot2_3.3.2     tidyverse_1.3.0   sen2r_1.4.0      

loaded via a namespace (and not attached):
 [1] fs_1.5.0           lubridate_1.7.9.2  doParallel_1.0.16  rprojroot_2.0.2   
 [5] tools_4.0.3        backports_1.2.1    rgdal_1.5-19       R6_2.5.0          
 [9] KernSmooth_2.23-18 rgeos_0.5-5        DBI_1.1.0          lazyeval_0.2.2    
[13] colorspace_2.0-0   withr_2.3.0        prettyunits_1.1.1  tidyselect_1.1.0  
[17] processx_3.4.5     curl_4.3           compiler_4.0.3     cli_2.2.0         
[21] rvest_0.3.6        geojsonsf_2.0.1    scales_1.1.1       classInt_0.4-3    
[25] callr_3.5.1        foreign_0.8-81     R.utils_2.10.1     pkgconfig_2.0.3   
[29] dbplyr_2.0.0       rlang_0.4.9        readxl_1.3.1       rstudioapi_0.13   
[33] httpcode_0.3.0     generics_0.1.0     R.oo_1.24.0        Rcpp_1.0.5        
[37] munsell_0.5.0      fansi_0.4.1        abind_1.4-5        lifecycle_0.2.0   
[41] R.methodsS3_1.8.1  stringi_1.5.3      pkgbuild_1.1.0     jqr_1.2.0         
[45] grid_4.0.3         maptools_1.0-2     parallel_4.0.3     crayon_1.3.4      
[49] RcppTOML_0.1.7     lattice_0.20-41    stars_0.5-0        haven_2.3.1       
[53] geojson_0.3.4      hms_0.5.3          ps_1.5.0           knitr_1.30        
[57] pillar_1.4.7       codetools_0.2-18   crul_1.0.0         reprex_0.3.0      
[61] XML_3.99-0.5       glue_1.4.2         V8_3.4.0           data.table_1.13.4 
[65] remotes_2.2.0      modelr_0.1.8       vctrs_0.3.5        foreach_1.5.1     
[69] cellranger_1.1.0   gtable_0.3.0       assertthat_0.2.1   xfun_0.19         
[73] lwgeom_0.2-5       broom_0.7.2        e1071_1.7-4        class_7.3-17      
[77] iterators_1.0.13   units_0.6-7        ellipsis_0.3.1    
```
packageVersion("sen2r")
```{r}
[1] ‘1.4.0’
```
sen2r::load_binpaths()
```{r}
$gdalinfo
[1] "/usr/bin/gdalinfo"

$ogrinfo
[1] "/usr/bin/ogrinfo"

$gdal_translate
[1] "/usr/bin/gdal_translate"

$gdalwarp
[1] "/usr/bin/gdalwarp"

$gdalbuildvrt
[1] "/usr/bin/gdalbuildvrt"

$gdaldem
[1] "/usr/bin/gdaldem"

$gdal_calc
[1] "/usr/bin/gdal_calc.py"

$gdal_polygonize
[1] "/usr/bin/gdal_polygonize.py"

$gdal_fillnodata
[1] "/usr/bin/gdal_fillnodata.py"

attr(,"path")
[1] "/home/vyago/.sen2r/paths.json"
```

**Comment by ranghetti** [comment] 2021-01-29 12:35
Hi, I am quite busy in this period, I will deepen this as soon as possible (more or less by the half of February, after the other open issues).
Nevertheless, errors suggest a problem  in the SciHub connection rather than a bug: please retry during next days and let me know if the problem will be still present.

**Comment by ranghetti** [comment] 2021-02-03 13:26
@VicenteYago before having a look to this, can you confirm to have re-tried? If so and if the problem is still there, please report again your output.

**Comment by VicenteYago** [comment] 2021-02-12 12:06
Ok, i just ran the example in the docker version of sen2r:

```{r}
> example_extent <- "./pilotoV2.geojson"
> output <-  sen2r(param_list = "./inputsV1-4-0-issue.json")
[2021-02-12 11:55:31] #### Starting sen2r execution. ####

The parameter file was created with an old version of the package:
would you like to open a GUI and check that the input parameters are
correct? (y/n)
Alternatively, press ESC to interrupt and check the parameter file
manually.
... n
Loading required namespace: stringi
Registered S3 method overwritten by 'geojsonlint':
  method         from 
  print.location dplyr
[2021-02-12 11:55:43] Searching for available SAFE products on
       SciHub...
[2021-02-12 11:55:43] Downloading and creating the vector of Sentinel-2
       tiles (this happens once)...
  |======================================================================| 100%
  |======================================================================| 100%
although coordinates are longitude/latitude, st_union assumes that they are planar
[2021-02-12 11:55:57] Computing output names...
Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
[2021-02-12 11:55:58] Starting to download the required level-2A SAFE
       products.
[2021-02-12 11:55:58] Check if products are available for download...
[2021-02-12 11:55:59] Downloading Sentinel-2 image 1 of 1
       (S2A_MSIL2A_20190225T105021_N0211_R051_T30SXH_20190225T134315.SAFE)...
  |======================================================================| 100%
Error in { : 
  task 1 failed - "task 1 failed - "task 1 failed - "zip file './l2a/S2A_MSIL2A_20190225T105021_N0211_R051_T30SXH_20190225T134315.SAFE.zip' cannot be opened"""

```

Here is the content of the l2a/ folder: 

```{bash}
-rw-r--r-- 1 root root 22330937 Feb 12 11:56 S2A_MSIL2A_20190225T105021_N0211_R051_T30SXH_20190225T134315.SAFE.zip

```
For further insight i executed this command in terminal: 
```{bash}
$ unzip l2a/S2A_MSIL2A_20190225T105021_N0211_R051_T30SXH_20190225T134315.SAFE.zip 
```

```{bash}
Archive:  l2a/S2A_MSIL2A_20190225T105021_N0211_R051_T30SXH_20190225T134315.SAFE.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of l2a/S2A_MSIL2A_20190225T105021_N0211_R051_T30SXH_20190225T134315.SAFE.zip or
        l2a/S2A_MSIL2A_20190225T105021_N0211_R051_T30SXH_20190225T134315.SAFE.zip.zip, and cannot find l2a/S2A_MSIL2A_20190225T105021_N0211_R051_T30SXH_20190225T134315.SAFE.zip.ZIP, period.

```
It looks the .SAFE file is corrupted, should I report to copernicus ?

**Comment by ranghetti** [comment] 2021-02-12 12:51
This is the same case encountered some days ago and reported in #381. After reading it, you can verify that, currently:
- https://scihub.copernicus.eu/dhis/odata/v1/Products('043637be-2810-424a-9be4-a4d9a4c8f311')/Online/$value is returning correctly False, while
- https://scihub.copernicus.eu/apihub/odata/v1/Products('043637be-2810-424a-9be4-a4d9a4c8f311')/Online/$value is returning True and an invalid SAFE can be downloaded.

Yes, please, report it to Copernicus support (you can refer to my communication - ticket n. CDS-109240 - which is reported in that issue).

**Comment by jburmistrova** [comment] 2021-02-19 00:35
Hi, I am having the same issues you list in the 2 bullet points (apihub is returning true and an invalid safe can be downloaded and I cannot unzip the downloaded file or open it in SNAP, and dhus is just giving me a 403 Forbidden). I emailed Copernicus support letting them know and cited your ticket number.

**Comment by ranghetti** [comment] 2021-02-19 08:13
@jburmistrova I answered you in #381 (this issue was opened for a different problem).
@VicenteYago I am closing this to avoid confusion: to continue with your last problem use #381; in case you still encounter the original problem, reopen and continue here.

**Closed by ranghetti** 2021-02-19 08:13 UTC
Labels: assistance
