### ISSUE TITLE
Use tiles_intersects() to find the tiles which fully cover an AOI

### ISSUE THREAD

**Issue by xbailleau** [ranghetti/sen2r#393] opened 2021-03-18 11:28 UTC
**Bug description**

Hello, 
when using tiles_intesects with an extent, I had some problems with extent which cover a tile hedge (so tile extent do not cover the entire extent) this cause some errors when loading tile raster, to overcome this case I changed the "st_intersects" on line 67 to "st_covered_by" and now works well
Thanks for this very usefull package, congrats !!
Best. Xavier Bailleau

**Comment by ranghetti** [comment] 2021-03-18 13:01
Hello, I do not understand your case: can you provide a reproducible example of a situation which caused you problems?

**Comment by xbailleau** [comment] 2021-03-18 15:59
![temp](https://user-images.githubusercontent.com/58946967/111650096-4217c480-8805-11eb-9458-4eaae1369176.png)
Hi here is a picture of my situation, using tiles_intersects (all=TRUE)  for that field yield 31UCQ 30UYV 31UCP 30UYU which is correct on intersection point of vue, but, in my case, I need that the tile cover the entire field because I load all the corresponding sentinel rasters, so only tiles 31UCP 30UYU 30UYV are good candidates and 31UCQ has to be discarded because it only partially cover the field. In my case, this is important because I noted that, along a growing season, using only rasters from one tile can miss some available images. If you try to download a raster for that field from tile 31UCQ you will have an error (non overlaping extent between raster and field polygon)

**Comment by ranghetti** [comment] 2021-03-18 16:16
A reproducible example is a piece of code which everyone can run. In your case, I need:
1. the vector you are using (you can attach it as KML, geopackage or shapefile, or load it using wetransfer and provide the link, convert in geoJSON and copy-paste it);
2. the piece of code you are running;
3. the R output you are receiving using standard sen2r package and the desired R output.

**Comment by xbailleau** [comment] 2021-03-18 20:10
Here is a piece of code, you just have to change the path if needed
I joined some rasters (cloud mask) because they are light it was just for the example
[tiles_intersects.zip](https://github.com/ranghetti/sen2r/files/6166929/tiles_intersects.zip)

**Comment by ranghetti** [comment] 2021-03-18 20:39
Ok, now the point is clear.

Although I understand what your aim is, the modify you suggest is not relevant for the package, since the function `tiles_intersects()` was written for a different scope: finding the tiles required to fully cover an area of interest, so to be downloaded, merged and processed. For this reason, in your case the output of interest for {sen2r} is a single tile (one among the three which covers the field), not all the three. The argument `all = TRUE` was added to use the function for different aims, like yours.

You can use the existing function for your scope, without the needing to modify it: simply use it with an output of class `sf`, and then filter the results:

```r
tiles_of_interest_v1_sf <- tiles_intersects(field,all=TRUE, out_format = "sf")
tiles_of_interest_v2_sf <- st_filter(tiles_of_interest_v1_sf, field, .predicate = st_covers)
tiles_of_interest_v2 <- tiles_of_interest_v2_sf$tile_id
```

**Comment by xbailleau** [comment] 2021-03-19 06:57
Yes your solution looks very good ! thx

**Closed** 2021-03-19 07:32 UTC
Labels: question
