### ISSUE TITLE
"DLL load failed" launching Python-based GDAL commands

### ISSUE THREAD

**Issue by retteb** [ranghetti/sen2r#234] opened 2019-11-05 14:27 UTC
Hi, 
I a new user of sen2r. When load sen2r(), i got error same with issues in #231. I follow suggestions in #231 and other related issues, but it still does not work.

Below is error report and related infromation:

```
> sen2r()
[2019-11-05 21:58:39] Starting sen2r execution.
GDAL version in use: 2.4.1
Error in py_module_import(module, convert = convert) : 
  ImportError: DLL load failed: 找不到指定的程序。

Detailed traceback: 
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\osgeo\__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\osgeo\__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
此外: Warning messages:
1: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="": 文件名、目录名或卷标语法不正确。
2: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="": 文件名、目录名或卷标语法不正确。
> Sys.getenv("PATH")
[1] "C:\\OSGeo4W64\\bin;C:\\OSGEO4~1\\apps\\Python27;C:\\Program Files\\R\\R-3.6.1\\bin\\x64;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\ProgramData\\Oracle\\Java\\javapath;c:\\Rtools\\bin;c:\\Rtools\\mingw_32\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Users\\kun\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Program Files (x86)\\SSH Communications Security\\SSH Secure Shell;C:\\Users\\kun\\AppData\\Roaming\\TinyTeX\\bin\\win32"
> Sys.getenv("PYTHONHOME")
[1] "C:\\OSGEO4~1\\apps\\Python27"
> Sys.getenv("PYTHONPATH")
[1] "C:\\OSGEO4~1\\apps\\Python27\\Lib"
> sen2r:::load_binpaths()
$aria2c
[1] "D:\\aria2\\aria2c.exe"

$sen2cor
[1] "D:\\Sen2Cor\\Sen2Cor-02.05.05-win64\\L2A_Process.bat"

$gdalinfo
[1] "C:\\OSGEO4~1\\bin\\gdalinfo.exe"

$ogrinfo
[1] "C:\\OSGEO4~1\\bin\\ogrinfo.exe"

$gdal_translate
[1] "C:\\OSGEO4~1\\bin\\GDAL_T~1.EXE"

$gdalwarp
[1] "C:\\OSGEO4~1\\bin\\gdalwarp.exe"

$gdalbuildvrt
[1] "C:\\OSGEO4~1\\bin\\GDALBU~1.EXE"

$gdaldem
[1] "C:\\OSGEO4~1\\bin\\gdaldem.exe"

$python
[1] "C:\\OSGEO4~1\\bin\\python.exe"

$gdal_calc
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_C~1.PY"

$gdal_polygonize
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_P~2.PY"

$gdal_fillnodata
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_F~1.PY"

attr(,"path")
[1] "~/.sen2r/paths.json"
#=============================================================
sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

> sen2r:::init_python()
GDAL version in use: 2.4.1
Error in py_module_import(module, convert = convert) : 
  ImportError: DLL load failed: 找不到指定的程序。

Detailed traceback: 
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\osgeo\__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\osgeo\__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
```

**Comment by ranghetti** [comment] 2019-11-05 15:38
Hi, 
unfortunately I am not able to replicate this error, which is affecting several users. 

> I follow suggestions in #231 and other related issues, but it still does not work.

Can you please detail which suggestions did you already followed? In particular:
1. did you check that `gdal-python` is installed through OSGeo4W?
2. Did you try reinstalling / updating all the packages with OSGeo4W installer?

Moreover, post the output of
```r
sen2r:::init_python()
```

**Comment by retteb** [comment] 2019-11-06 05:09
Hi,
     I installed gdal-python through OSGeo4W. I have reinstalled it serval times.
     I tried both the old  and newest  session of sen2r. The problem always there.
     Moreover, to aviod confusions, i unintalled QGIS in my computer. It does not work.

    Below is the results of  sen2r:::init_python()  :

GDAL version in use: 2.4.1
Error in py_module_import(module, convert = convert) : 
  ImportError: DLL load failed: 找不到指定的模块。

Detailed traceback: 
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\osgeo\__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\osgeo\__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)

**Comment by ranghetti** [comment] 2019-11-07 08:36
Unfortunately these are problems related to GDAL installation, which are very difficult to investigate without having the hands on the system on which they are occurring.
If you have reinstalled gdal-python but not the whole OSGeo4W, try doing it (this should solve in case the missing DLL is part of OSGEo4W; it sohuld not if the missing DLL is part of Windows).

Then, open the OSGeo Shell and try the followings:
```
gdalinfo --version

python
import gdal
import __builtin__
```

**Comment by lbusett** [comment] 2019-11-07 12:32
Maybe this can help?

https://gis.stackexchange.com/a/223238

(that is, setting  / modifying Windows environment variables, outside R)

**Comment by ranghetti** [comment] 2019-11-07 16:37
@lbusett, currently this could hel solving the issue _outside_ sen2r, but not inside, because using OSGe04W GDAL / Python is a sen2r mandatory requirement since sen2r v. 1.1.0. But it is useful to test this way in order to understand if the problem is related to OSGeo or to the Windows system's DLLs.

@retteb, please try first to run the commands specified in my previous comment, then try following the @lbusett's suggestion, and check if, in that way, you are able to run `from osgeo import gdal` (as shown in the posted link). If so, I will edit the sen2r code in order to accept this GDAL/Python installation.

**Comment by retteb** [comment] 2019-11-09 08:45
Hi all,
      Thanks for all for your suggestion.
      I am in the field work and I will try them as soon as possible. 
      Later, i will let you know the results.

**Comment by retteb** [comment] 2019-11-26 03:55
Hi ranghetti,
     Sorry for late response.
     I follow @lbusett's suggestion to install GDAL. But sen2r cannot find the path to GDAL. 
     The error information as below:
#----------------------------------------
sen2r()
[2019-11-26 11:52:17] Starting sen2r execution.
Searching for a valid GDAL installation...
error: GDAL was not found within the defined GDAL path, please install it or define another value for argument "gdal_path".

**Comment by ranghetti** [comment] 2019-11-26 07:17
> sen2r cannot find the path to GDAL.

This was expected: as I commented in my last post, sen2r is set to recognise and use only OSGeo4W installations.

What I need to understand if @lbusett's suggestion is helpful to solve the issue is:

> @retteb, please try first to run the commands specified in my previous comment, then try following the @lbusett's suggestion, and check if, in that way, you are able to run `from osgeo import gdal` (as shown in the posted link). If so, I will edit the sen2r code in order to accept this GDAL/Python installation.

If somepthing is not clear, feel free to ask.

**Comment by lbusett** [comment] 2019-11-26 07:54
It may be a gdal3 issue. @ranghetti: have a look at https://github.com/gearslaboratory/gdalUtils/commit/27743deb5b83e03e05405943eadb29dd98f1f5e7

I'd suggest trying installing the devel version of gdalUtils from github and see if it solves somehow.

**Comment by ranghetti** [comment] 2019-11-26 08:11
@lbusett **gdalUtils** is no more a **sen2r** dependency; nevertheless I encountered a problem with GDAL 3 and **reticulate** on Windows (b327b68b0b501aa70859b2f50b637e5a8cce3a57, which however does not occur iwth GDAL 3 on Linux). I will investigate if a newer version of **reticulate** improved something on Windows.

**Comment by lbusett** [comment] 2019-11-26 08:24
Oh, sorry. I had trouble for that gdalUtils issue in MODIStsp and the error looked similar.

**Comment by ranghetti** [comment] 2019-11-26 12:33
I verified, this issue does not seem to be related with **reticulate** management of GDAL 3: the error occurs at `init_python()' stage, while, on the Windows machine which I used for test, this step is performed correctly.

**Comment by lbusett** [comment] 2019-11-26 14:07
@ranghetti maybe i misinterpreted, bu the error seems to have changed. Now it is:

 Searching for a valid GDAL installation...
error: GDAL was not found within the defined GDAL path, please install it or define another value for argument "gdal_path".

**Comment by ranghetti** [comment] 2019-11-26 16:03
> @ranghetti maybe i misinterpreted, bu the error seems to have changed. Now it is:
> 
> Searching for a valid GDAL installation...
> error: GDAL was not found within the defined GDAL path, please install it or define another value for argument "gdal_path".

Maybe because the OSGeo4W GDAL was removed before installing the new one (@retteb is it?). But in both the cases it occurs at `init_python()` stage: for a DLL problem (first case) or because OSGeo GDAL was not found (in the second). Conversely, the error which I was referencing is not related to this one, since it occurs at a later stage.

**Comment by ranghetti** [comment] 2019-11-30 16:43
Some improvements which I did recently should have fixed this problem. 
The reason was twofold: 1. a missing 'proj.db` file in **rgdal**; 2. the path of the Python GDAL applications was not added to PATH variable in **sen2r**.

Before performing the test which I indicated you some days before, you can simply install the latest **sen2r** version from GitHub and see if the error was solved:
```r
remotes::install_github("ranghetti/sen2r")
```
If this is not sufficient, I look forward for your feedback regarding the "old" test (if you can not perform it for any reason, please notify that).

Let me know,

**Comment by retteb** [comment] 2019-12-03 05:06
Hi ranghetti,
   Thanks for  your effort.  
   I reinstall the new version, but got the same error.
#-----------------------------------------------------------   
> sen2r()
[2019-12-03 13:03:04] Starting sen2r execution.
GDAL version in use: 3.0.2
Error in py_module_import(module, convert = convert) : 
  ImportError: DLL load failed: 找不到指定的程序。

Detailed traceback: 
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\osgeo\__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\osgeo\__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
此外: Warning messages:
1: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="": 文件名、目录名或卷标语法不正确。
2: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="": 文件名、目录名或卷标语法不正确。
> Sys.getenv("PATH")
[1] "C:/OSGEO4~1/bin;C:/OSGEO4~1/bin;C:\\Program Files\\R\\R-3.6.1\\bin\\x64;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\ProgramData\\Oracle\\Java\\javapath;c:\\Rtools\\bin;c:\\Rtools\\mingw_32\\bin;C:\\Windows\\System32;C:\\Windows;C:\\Windows\\System32\\wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Users\\kun\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Program Files (x86)\\SSH Communications Security\\SSH Secure Shell;C:\\Users\\kun\\AppData\\Roaming\\TinyTeX\\bin\\win32"
> Sys.getenv("PYTHONHOME")
[1] "C:/OSGEO4~1/apps/Python27"
> Sys.getenv("PYTHONPATH")
[1] "C:/OSGEO4~1/apps/Python27/Lib"
> sen2r:::load_binpaths()
$aria2c
[1] "D:\\aria2\\aria2c.exe"

$sen2cor
[1] "D:\\Sen2Cor\\Sen2Cor-02.05.05-win64\\L2A_Process.bat"

$gdalinfo
[1] "C:\\OSGEO4~1\\bin\\gdalinfo.exe"

$ogrinfo
[1] "C:\\OSGEO4~1\\bin\\ogrinfo.exe"

$gdal_translate
[1] "C:\\OSGEO4~1\\bin\\GDAL_T~1.EXE"

$gdalwarp
[1] "C:\\OSGEO4~1\\bin\\gdalwarp.exe"

$gdalbuildvrt
[1] "C:\\OSGEO4~1\\bin\\GDALBU~1.EXE"

$gdaldem
[1] "C:\\OSGEO4~1\\bin\\gdaldem.exe"

$python
[1] "C:\\OSGEO4~1\\bin\\python.exe"

$gdal_calc
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_C~1.PY"

$gdal_polygonize
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_P~2.PY"

$gdal_fillnodata
[1] "C:\\OSGEO4~1\\bin\\python.exe C:\\OSGEO4~1\\bin\\GDAL_F~1.PY"

attr(,"path")
[1] "~/.sen2r/paths.json"

**Comment by ranghetti** [comment] 2019-12-03 06:50
I am sorry this did not help. I can not do anything else until you will perform the "old" test on the standalone GDAL, so I am closing this issue for now. Feel free to reopen it by providing the required feedback.

**Closed by ranghetti** 2019-12-03 06:50 UTC
